### ISSUE TITLE
Research on frameworks

### ISSUE THREAD

**Issue by andyruto** [andyruto/ShiftPLAN#8]
Testing different frameworks:

- JFoenix (Material Design for JavaFX)
- F̵l̵u̵x̵F̵X̵ ̵(̵F̵L̵U̵X̵ ̵b̵a̵s̵e̵d̵ ̵f̵r̵a̵m̵e̵w̵o̵r̵k̵ ̵f̵o̵r̵ ̵r̵e̵a̵c̵t̵i̵v̵e̵ ̵G̵U̵I̵ ̵d̵e̵v̵e̵l̵o̵p̵m̵e̵n̵t̵ ̵l̵i̵k̵e̵ ̵R̵e̵a̵c̵t̵J̵S̵)̵
- Doctrine (Code-First Framework for multiple DBMS)
- JFXtras (Calender view for JavaFX 8)

**Comment by ghost** [comment]
Decision against FluxFX because of Project-Deadline.
Adding JFXtras for calender view.
