### ISSUE TITLE
Is it a web application?

### ISSUE THREAD

**Issue by astrakid** [andyruto/ShiftPLAN#9]
hi,
sorry for raising an issue for this simple question. is this tool usable as web application?
regards,
andre

**Comment by lululujojo123** [comment]
OMG. I am so sorry for answering that question so late. We had to drop the development on our idea temporarily. But now we want to "relaunch" (we never hat a working version xD) the project as a Angular WebApp in our university project.

And yes. Our idea was, to provide a easy to deploy application. Just register for a web hosting service. Unzip the application on the server. And your ready to use. And we try to provide a more or less secure application also on web servers without secure access over https by implementing encryption for some very critical data.

Hopefully that answers your question. And if we are able to finish a more or less usable version within that semester, we would be happy if it could maybe help you with your HR organization. :)

**Comment by astrakid** [comment]
yes, this answer helps me. good luck, if you need testers, let me know.
kind regards,
andre
